/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _musMonchi_h_
#define _musMonchi_h_
//---------------------------------------------------------------------------------
extern const unsigned char musMonchi[];
extern const int musMonchi_size;
//---------------------------------------------------------------------------------
#endif //_musMonchi_h_
//---------------------------------------------------------------------------------
